"""Coluna ID

Revision ID: cc366241eb42
Revises: 
Create Date: 2024-06-04 21:31:52.024388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc366241eb42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('nome', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('sobre_nome', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=128, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('foto_perfil', sa.VARCHAR(length=120, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('data_criado', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('nome', name='PK__tb_usuar__6F71C0DDD8335BE0')
    )
    # ### end Alembic commands ###
